# HueOS Configuration

# Kernel configuration
KERNEL_NAME=HueOS
KERNEL_VERSION=0.1.0
KERNEL_LOAD_ADDRESS=0x100000

# Compiler settings
TARGET_ARCH=i686-elf
USE_CROSS_COMPILER=no

# Features
ENABLE_HYPERV=yes
ENABLE_PAGING=yes
ENABLE_HEAP=yes
DEBUG_OUTPUT=yes

# Memory configuration
STACK_SIZE=16384
HEAP_START=0x200000
MAX_MEMORY=0x10000000

# Build settings
OPTIMIZATION_LEVEL=2
WARNINGS_AS_ERRORS=no

# Testing configuration  
DEFAULT_QEMU_MEMORY=128M
ENABLE_KVM=auto